services:
    demo_widget.listener:
        class: MorgenBord\DemoWidgetBundle\EventListener\RegisterWidgetListener
        tags:
            - { name: kernel.event_listener, event: morning_bord.register_widget }